{"name": "Успешный вход курьера в систему", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался код состояния 200, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x000001B676DC7FD0>\n\n    @allure.title(\"Успешный вход курьера в систему\")\n    def test_authorization_with_valid_login_and_password(self):\n        response = login_courier(TestDataLogin.valid_login_and_valid_login)\n>       assert response.status_code == 200, f\"Ожидался код состояния 200, но был получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался код состояния 200, но был получен 404. Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_courier_login.py:10: AssertionError"}, "steps": [{"name": "Вход курьера в систему", "status": "passed", "parameters": [{"name": "credentials", "value": "{'login': 'Petrov', 'password': '12345', 'firstName': 'hero'}"}], "start": 1704721379881, "stop": 1704721380246}], "start": 1704721379881, "stop": 1704721380247, "uuid": "22c76f1e-738d-4a1c-bfed-e1774a3ee45c", "historyId": "174b95c871014957dfff18e17300d76a", "testCaseId": "174b95c871014957dfff18e17300d76a", "fullName": "tests.test_courier_login.TestCourierLogin#test_authorization_with_valid_login_and_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "LAPTOP-1KK7H688"}, {"name": "thread", "value": "10096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}