{"uid":"925f0643193428ab","name":"если авторизоваться под несуществующим пользователем, запрос возвращает ошибку;","fullName":"tests.test_courier_login.TestCourierLogin#test_authorization_without_login_and_password","historyId":"5f3dc43b496043b2f17f52fcdc8a218c","time":{"start":1704721381043,"stop":1704721381365,"duration":322},"status":"failed","statusMessage":"AssertionError: Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 'Not Found.' == 'Учетная запись не найдена'\n  - Учетная запись не найдена\n  + Not Found.","statusTrace":"self = <tests.test_courier_login.TestCourierLogin object at 0x000001B677117B10>\n\n    @allure.title(\"если авторизоваться под несуществующим пользователем, запрос возвращает ошибку;\")\n    def test_authorization_without_login_and_password(self):\n        response = login_courier(TestDataLogin.non_existent_user)\n        assert response.status_code == 404, f\"Ожидался код состояния 404, но был получен {response.status_code}. Ответ: {response.text}\"\n>       assert response.json()[\"message\"] == \"Учетная запись не найдена\", f\"Ответ: {response.text}\"\nE       AssertionError: Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 'Not Found.' == 'Учетная запись не найдена'\nE         - Учетная запись не найдена\nE         + Not Found.\n\ntests\\test_courier_login.py:35: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nassert 'Not Found.' == 'Учетная запись не найдена'\n  - Учетная запись не найдена\n  + Not Found.","statusTrace":"self = <tests.test_courier_login.TestCourierLogin object at 0x000001B677117B10>\n\n    @allure.title(\"если авторизоваться под несуществующим пользователем, запрос возвращает ошибку;\")\n    def test_authorization_without_login_and_password(self):\n        response = login_courier(TestDataLogin.non_existent_user)\n        assert response.status_code == 404, f\"Ожидался код состояния 404, но был получен {response.status_code}. Ответ: {response.text}\"\n>       assert response.json()[\"message\"] == \"Учетная запись не найдена\", f\"Ответ: {response.text}\"\nE       AssertionError: Ответ: {\"code\":404,\"message\":\"Not Found.\"}\nE       assert 'Not Found.' == 'Учетная запись не найдена'\nE         - Учетная запись не найдена\nE         + Not Found.\n\ntests\\test_courier_login.py:35: AssertionError","steps":[{"name":"Вход курьера в систему","time":{"start":1704721381043,"stop":1704721381365,"duration":322},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"credentials","value":"{'login': 'Petrov890890', 'password': 'dfuebw7685'}"}],"hasContent":true,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"attachmentStep":false,"stepsCount":1,"shouldDisplayMessage":true,"attachmentsCount":0},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_courier_login"},{"name":"subSuite","value":"TestCourierLogin"},{"name":"host","value":"LAPTOP-1KK7H688"},{"name":"thread","value":"10096-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_courier_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"925f0643193428ab.json","parameterValues":[]}